apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myimage-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cert
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - example.test.com
    secretName: myimage-cert
  rules:
  - host: example.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myimage-service
            port:
              number: 3000

---