apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: werewolf-ingress
  # namespace: nick
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cert
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - werewolf.nk.sytes.net
    secretName: werewolf-cert
  rules:
  - host: werewolf.nk.sytes.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: werewolf-service
            port:
              number: 5000
