services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "HelloWorld"
      MYSQL_DATABASE: "Test"
    ports:
      - "43306:3306"
    volumes:
      - ./data:/var/lib/mysql/