services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "47017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=HelloWorld
    volumes:
      - ./mongo-data:/data/db