services:
  postgres:
   container_name: postgres
   image: postgres:14.13
   restart: always
   environment:
     POSTGRES_DB: test 
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: HelloWorld
   ports:
     - "45432:5432"
   volumes:
     - ./infile:/infile
     - ./data:/var/lib/postgresql/data/